pipeline {
    agent {
        label 'AGENT-1'
    }

    environment { 
        REGION = "us-east-1"
        ACC_ID = "413335224836"
        PROJECT = "roboshop"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }

    stages {

        stage('destroy') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh '''
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform destroy -auto-approve
                        '''
                    }
                }
            }
        }

    }
}
